name: Deploy to Heroku

on:
  pull_request:
    branches:
      - develop_release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | heroku auth:token

      - name: Add Heroku remote
        run: heroku git:remote -a calm-taiga-00119

      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:refs/heads/main --force
