name: Deploy to Heroku

on:
  push:
    branches:
      - develop_release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: calm-taiga-00119 #Must be unique in Heroku
          heroku_email: samuelfumerohdez@gmail.com
